# Todo: 每次 commit 之前务必清除账号密码

# 刷课配置
project:
  skip-finished: true  # 跳过已完成任务（暂不支持）


# iSmart 客户端配置
browser:
  executable: Z:\iSmart\client\iSmart.exe  # 客户端可执行文件的路径
  args:  # 启动 iSmart 客户端时额外提供的参数
    - --disable-web-security
  port: 9222  # devTools 调试端口

# 用户配置（务必保持账号密码与 iSmart 中已登录的相同）
user:
  username: <用户名>  # 手机号
  password: <密码>  # 密码
